### ISSUE TITLE
use `click.edit` instead of our own function to prepare pull request

### ISSUE THREAD

**Issue by TomasTomecek** [packit/upsint#63]
TODO:

* [ ] replace our own `utils.prompt_for_pr_content` with `click.edit`
* [ ] write a test case for creating PRs

Have a look at: https://click.palletsprojects.com/en/8.0.x/utils/#launching-editors

You don't even need this :)

_Originally posted by @mfocko in https://github.com/packit/upsint/pull/62#discussion_r725147042_

**Comment by prkhrsrvstv1** [comment]
Hi @TomasTomecek I can get this done quickly. Please assign this issue to me.

**Comment by mfocko** [comment]
@prkhrsrvstv1 Hi, I have assigned you, in case you have any questions don't hesitate to open PR and raise it up :) Also I would like to point you to our contribution guidelines for [all of our projects](https://github.com/packit/contributing).
